#:schema https://json.schemastore.org/pyproject.json
##
## Programmable interfaces for finding homes.
##


[build-system]

requires      = [ 'flit_core ~= 3.12' ]
build-backend = 'flit_core.buildapi'


[project]

name    = 'homefinder'
version = '1.0.0'

readme      = './readme.md'
description = 'Programmable interfaces for finding homes.'
license     = 'GPL-2.0-only'

requires-python = '~= 3.12'
dependencies    = [
	'openpyxl ~= 3.1.0'
]

[[project.authors]]

name  = 'Martins Zariņš'
email = 'pasts@zarins.zip'

[[project.authors]]

name  = 'Rauls Ulvis Grimza'
email = 'rrauls12345@gmail.com'

