#:schema https://json.schemastore.org/pyproject.json
##
## The `homefinder` project
##


[dependency-groups]

dev = [
	"openpyxl>=3.1.5",
	'pdoc ~= 15.0.0',
]

[tool.uv.workspace]

members = [ './packages/*' ]

