#:schema https://json.schemastore.org/pyproject.json
##
## Find homes on SS.lv.
##


[build-system]

requires      = [ 'flit_core ~= 3.12' ]
build-backend = 'flit_core.buildapi'


[project]

name    = 'sslv-py'
version = '0.0.1'

readme      = 'readme.md'
description = 'Find homes on SS.lv.'
license     = 'GPL-2.0-only'

requires-python = '~= 3.12'
dependencies    = [
	'homefinder ~= 0.0',
	'aiohttp ~= 3.11.0'
]

[tool.flit.module]

name = 'sslv'

[[project.authors]]

name  = 'Martins Zariņš'
email = 'pasts@zarins.zip'

[[project.authors]]

name  = 'Rauls ...'
email = 'rauls@example.com'

