#:schema https://json.schemastore.org/pyproject.json
##
## Functional interfaces for finding homes.
##


[build-system]

requires      = [ 'flit_core ~= 3.12' ]
build-backend = 'flit_core.buildapi'


[project]

name    = 'homefinder-lib'
version = '0.0.1'

readme      = './readme.md'
description = 'Functional interfaces for finding homes.'
license     = 'GPL-2.0-only'

requires-python = '~= 3.12'

[tool.flit.module]

name = 'homefinder'

[[project.authors]]

name  = 'Martins Zariņš'
email = 'pasts@zarins.zip'

[[project.authors]]

name  = 'Rauls ...'
email = 'rauls@example.com'

